package main

import (
	"fmt"
	"log"
	"strings"

	home "pbootcms-go/apps/home/controller"
	"pbootcms-go/apps/admin/model"
	"pbootcms-go/apps/admin/model/content"
	"pbootcms-go/apps/admin/model/member"
	"pbootcms-go/apps/admin/model/system"
	"pbootcms-go/apps/admin/seed"
	"pbootcms-go/apps/common/middleware"
	"pbootcms-go/apps/common/parser"
	"pbootcms-go/apps/route"
	"pbootcms-go/config"
	"pbootcms-go/core/basic"

	"github.com/gin-gonic/gin"
)

func main() {
	cfg := config.Load("config/config.json")

	if err := model.InitDB(cfg); err != nil {
		log.Fatalf("Database init failed: %v", err)
	}
	defer model.CloseDB()

	// AutoMigrate all models: system + content + member
	system.AutoMigrate()
	content.AutoMigrate()
	member.AutoMigrate()

	// Seed initial data (admin user, menus, configs, etc.)
	seed.Init()

	basic.InitViewEngine(cfg.App.TemplateDir, cfg.App.AdminTemplateDir)

	tagParser := parser.New()
	store, err := parser.NewTemplateStore(cfg.App.TemplateDir, tagParser)
	if err != nil {
		log.Fatalf("Template engine init failed: %v", err)
	}
	defer store.Close()

	if !cfg.App.Debug {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.Default()

	// URL 規範化：剝離 .html 後綴（類似 nginx rewrite）
	// 讓 /content/7.html 和 /content/7 都能訪問同一頁面
	// gin 路由匹配先於中間件，需用 HandleContext 重新路由
	r.Use(func(c *gin.Context) {
		if strings.HasSuffix(c.Request.URL.Path, ".html") {
			c.Request.URL.Path = strings.TrimSuffix(c.Request.URL.Path, ".html")
			r.HandleContext(c)
			c.Abort()
			return
		}
		c.Next()
	})

	r.Static("/static", cfg.App.StaticDir)
	// PbootCMS 兼容: 前台模板靜態資源（CSS/JS/圖片）
	r.Static("/template/default/static", "template/default/static")

	route.SetupAdminRoutes(r)

	fc := home.NewFrontController(store)

	r.GET("/", fc.Index)
	r.GET("/search", fc.Search)
	r.GET("/tags", fc.Tags)
	r.GET("/message", fc.Message)
	r.POST("/message", fc.Message)
	r.GET("/api/visits", fc.Visits)
	r.GET("/api/checkcode", fc.CheckCode)

	// 會員系統路由
	r.GET("/login", fc.Login)
	r.POST("/login", fc.Login)
	r.GET("/register", fc.Register)
	r.POST("/register", fc.Register)
	r.GET("/logout", fc.Logout)
	r.GET("/ucenter", fc.Ucenter)
	r.GET("/umodify", fc.Umodify)
	r.POST("/umodify", fc.Umodify)

	// Dynamic content routes — generated by sortToMap/contentToMap
	// when urlname is empty. PbootCMS convention:
	//   /sort/{scode}    → list page of the sort (scode 從不改變)
	//   /content/{id}     → content detail page (id is monotonic)
	r.GET("/sort/:scode", fc.SortByScode)
	r.GET("/content/:id", fc.ContentByID)

	r.NoRoute(func(c *gin.Context) {
		original := c.Request.URL.Path
		// PbootCMS 模板生成的 URL 大小寫可能與 Go 路由不一致
		// (e.g. /admin/Content/index vs /admin/content/index)
		// 先嘗試 lowercase 歸一化
		lower := strings.ToLower(original)
		if strings.HasPrefix(lower, "/admin/") && lower != original {
			newPath := middleware.RewriteAdminPath(lower)
			c.Request.Header.Set("X-Original-Path", original)
			c.Request.URL.Path = newPath
			r.HandleContext(c)
			return
		}
		// 嘗試 PbootCMS 原版 URL → Go 版路徑重寫
		newPath := middleware.RewriteAdminPath(original)
		if newPath != original {
			c.Request.Header.Set("X-Original-Path", original)
			c.Request.URL.Path = newPath
			r.HandleContext(c)
			return
		}
		// 不匹配 admin 路径，走前台内容页
		fc.ContentPage(c)
	})

	addr := fmt.Sprintf(":%d", cfg.App.Port)
	log.Printf("PbootCMS-Go started at http://localhost%s", addr)
	log.Printf("Admin panel: http://localhost%s/admin", addr)
	if err := r.Run(addr); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}
